/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UCNDiscordBot;

import javax.security.auth.login.LoginException;

import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.requests.GatewayIntent;

public class App extends ListenerAdapter {
    private static String discordToken = new GetAPIKey().getDiscordKey();

    public static void main(String[] args) {
        // Create a new JDABuilder instance
        JDABuilder builder = JDABuilder
                .createDefault(discordToken);

        // Set the activity for the session
        builder.setActivity(Activity.watching("på dig i badet"));

        // Enable gateway intent to read messages
        builder.enableIntents(GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_MEMBERS);

        // Add the listeners
        builder.addEventListeners(new MessageListener());

        // Build the JDA instance
        try {
            builder.build();
        } catch (LoginException e) {
            e.printStackTrace();
        }
    }
}