/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UCNDiscordBot;

import javax.security.auth.login.LoginException;

import UCNDiscordBot.MusicPlayer.*;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

public class App extends ListenerAdapter {
    private static String discordToken = new GetAPIKey().getDiscordKey();

    public static void main(String[] args) {
        // Create a new JDABuilder instance
        JDABuilder builder = JDABuilder
                .create(discordToken, GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_MESSAGES,
                        GatewayIntent.GUILD_VOICE_STATES, GatewayIntent.MESSAGE_CONTENT);

        // Set the activity for the session
        builder.setActivity(Activity.watching("på dig i badet"));

        // Disable cache
        builder.disableCache(CacheFlag.ACTIVITY, CacheFlag.EMOJI, CacheFlag.STICKER, CacheFlag.CLIENT_STATUS,
                CacheFlag.ONLINE_STATUS);

        // Add the listeners
        builder.addEventListeners(new MessageListener());
        builder.addEventListeners(new MusicPlayer());

        // Build the JDA instance
        try {
            builder.build();
        } catch (LoginException e) {
            e.printStackTrace();
        }
    }
}